//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediKit.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int Id { get; set; }
        public string Producto { get; set; }
        public int Precio { get; set; }
        public int Cantidad { get; set; }
        public int Lote { get; set; }
        public int MarcaID { get; set; }
    
        public virtual Marcas Marcas { get; set; }
    }
}
