//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediKitWeb.MisServiciosWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Equipos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        private int PrecioField;
        
        private int CantidadField;
        
        private int LoteField;
        
        private int MarcaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Lote {
            get {
                return this.LoteField;
            }
            set {
                if ((this.LoteField.Equals(value) != true)) {
                    this.LoteField = value;
                    this.RaisePropertyChanged("Lote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MarcaID {
            get {
                return this.MarcaIDField;
            }
            set {
                if ((this.MarcaIDField.Equals(value) != true)) {
                    this.MarcaIDField = value;
                    this.RaisePropertyChanged("MarcaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MisServiciosWeb.MisServiciosSoap")]
    public interface MisServiciosSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MediKitWeb.MisServiciosWeb.HelloWorldResponse HelloWorld(MediKitWeb.MisServiciosWeb.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MediKitWeb.MisServiciosWeb.HelloWorldResponse> HelloWorldAsync(MediKitWeb.MisServiciosWeb.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ReadAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAll", ReplyAction="*")]
        MediKitWeb.MisServiciosWeb.ReadAllResponse ReadAll(MediKitWeb.MisServiciosWeb.ReadAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAll", ReplyAction="*")]
        System.Threading.Tasks.Task<MediKitWeb.MisServiciosWeb.ReadAllResponse> ReadAllAsync(MediKitWeb.MisServiciosWeb.ReadAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MediKitWeb.MisServiciosWeb.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MediKitWeb.MisServiciosWeb.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MediKitWeb.MisServiciosWeb.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MediKitWeb.MisServiciosWeb.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAll", Namespace="http://tempuri.org/", Order=0)]
        public MediKitWeb.MisServiciosWeb.ReadAllRequestBody Body;
        
        public ReadAllRequest() {
        }
        
        public ReadAllRequest(MediKitWeb.MisServiciosWeb.ReadAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadAllRequestBody {
        
        public ReadAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public MediKitWeb.MisServiciosWeb.ReadAllResponseBody Body;
        
        public ReadAllResponse() {
        }
        
        public ReadAllResponse(MediKitWeb.MisServiciosWeb.ReadAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MediKitWeb.MisServiciosWeb.Equipos[] ReadAllResult;
        
        public ReadAllResponseBody() {
        }
        
        public ReadAllResponseBody(MediKitWeb.MisServiciosWeb.Equipos[] ReadAllResult) {
            this.ReadAllResult = ReadAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MisServiciosSoapChannel : MediKitWeb.MisServiciosWeb.MisServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MisServiciosSoapClient : System.ServiceModel.ClientBase<MediKitWeb.MisServiciosWeb.MisServiciosSoap>, MediKitWeb.MisServiciosWeb.MisServiciosSoap {
        
        public MisServiciosSoapClient() {
        }
        
        public MisServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MisServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MisServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MisServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MediKitWeb.MisServiciosWeb.HelloWorldResponse MediKitWeb.MisServiciosWeb.MisServiciosSoap.HelloWorld(MediKitWeb.MisServiciosWeb.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MediKitWeb.MisServiciosWeb.HelloWorldRequest inValue = new MediKitWeb.MisServiciosWeb.HelloWorldRequest();
            inValue.Body = new MediKitWeb.MisServiciosWeb.HelloWorldRequestBody();
            MediKitWeb.MisServiciosWeb.HelloWorldResponse retVal = ((MediKitWeb.MisServiciosWeb.MisServiciosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MediKitWeb.MisServiciosWeb.HelloWorldResponse> MediKitWeb.MisServiciosWeb.MisServiciosSoap.HelloWorldAsync(MediKitWeb.MisServiciosWeb.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediKitWeb.MisServiciosWeb.HelloWorldResponse> HelloWorldAsync() {
            MediKitWeb.MisServiciosWeb.HelloWorldRequest inValue = new MediKitWeb.MisServiciosWeb.HelloWorldRequest();
            inValue.Body = new MediKitWeb.MisServiciosWeb.HelloWorldRequestBody();
            return ((MediKitWeb.MisServiciosWeb.MisServiciosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MediKitWeb.MisServiciosWeb.ReadAllResponse MediKitWeb.MisServiciosWeb.MisServiciosSoap.ReadAll(MediKitWeb.MisServiciosWeb.ReadAllRequest request) {
            return base.Channel.ReadAll(request);
        }
        
        public MediKitWeb.MisServiciosWeb.Equipos[] ReadAll() {
            MediKitWeb.MisServiciosWeb.ReadAllRequest inValue = new MediKitWeb.MisServiciosWeb.ReadAllRequest();
            inValue.Body = new MediKitWeb.MisServiciosWeb.ReadAllRequestBody();
            MediKitWeb.MisServiciosWeb.ReadAllResponse retVal = ((MediKitWeb.MisServiciosWeb.MisServiciosSoap)(this)).ReadAll(inValue);
            return retVal.Body.ReadAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MediKitWeb.MisServiciosWeb.ReadAllResponse> MediKitWeb.MisServiciosWeb.MisServiciosSoap.ReadAllAsync(MediKitWeb.MisServiciosWeb.ReadAllRequest request) {
            return base.Channel.ReadAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediKitWeb.MisServiciosWeb.ReadAllResponse> ReadAllAsync() {
            MediKitWeb.MisServiciosWeb.ReadAllRequest inValue = new MediKitWeb.MisServiciosWeb.ReadAllRequest();
            inValue.Body = new MediKitWeb.MisServiciosWeb.ReadAllRequestBody();
            return ((MediKitWeb.MisServiciosWeb.MisServiciosSoap)(this)).ReadAllAsync(inValue);
        }
    }
}
